package ve.com.abicelis.cryptomaster.ui.market;

import android.content.Context;
import android.graphics.Color;
import android.os.Bundle;
import android.support.annotation.NonNull;
import android.support.annotation.Nullable;
import android.support.design.widget.BaseTransientBottomBar;
import android.support.design.widget.CoordinatorLayout;
import android.support.design.widget.Snackbar;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;

import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;

import butterknife.BindView;
import butterknife.ButterKnife;
import lecho.lib.hellocharts.formatter.AxisValueFormatter;
import lecho.lib.hellocharts.formatter.SimpleAxisValueFormatter;
import lecho.lib.hellocharts.model.Axis;
import lecho.lib.hellocharts.model.AxisValue;
import lecho.lib.hellocharts.model.Line;
import lecho.lib.hellocharts.model.LineChartData;
import lecho.lib.hellocharts.model.PointValue;
import lecho.lib.hellocharts.view.LineChartView;
import ve.com.abicelis.cryptomaster.R;
import ve.com.abicelis.cryptomaster.application.Message;
import ve.com.abicelis.cryptomaster.ui.base.BaseFragment;
import ve.com.abicelis.cryptomaster.util.AttrUtil;

/**
 * Created by abicelis on 30/5/2018.
 */
public class MarketFragment extends BaseFragment implements MarketMvpView {

    public static final String COLOR_OF_FRAGMENT = "COLOR_OF_FRAGMENT";
    private int color;
    private Context mContext;

    @Inject
    MarketPresenter mMarketPresenter;

    @BindView(R.id.fragment_market_container)
    CoordinatorLayout mContainer;
    @BindView(R.id.fragment_market_total_chart)
    LineChartView mMarketCapChart;


    public MarketFragment() {
        // Required empty public constructor
    }

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        getPresenterComponent().inject(this);
        mMarketPresenter.attachView(this);

        if (getArguments() != null) {
            color = getArguments().getInt(COLOR_OF_FRAGMENT);
        }
    }


    @Override
    public View onCreateView(@NonNull LayoutInflater inflater, ViewGroup container,
                             Bundle savedInstanceState) {

        // Inflate the layout for this fragment
        View rootView = inflater.inflate(R.layout.fragment_market, container, false);
        ButterKnife.bind(this, rootView);

        mMarketPresenter.getMarketCapGraphData();

        mContainer.setBackgroundColor(Color.DKGRAY);
        return rootView;
    }

    @Override
    public void onAttach(Context context) {
        super.onAttach(context);
        mContext = context;
    }

    @Override
    public void onDetach() {
        super.onDetach();
        mContext = null;
    }

    @Override
    public void onDestroy() {
        super.onDestroy();
        mMarketPresenter.detachView();
    }

    @Override
    public void showMessage(Message message, @Nullable BaseTransientBottomBar.BaseCallback<Snackbar> callback) {
        //Not implemented
    }



    @Override
    public void showMarketCapGraph(List<PointValue> values) {

        Line line = new Line(values).setColor(Color.WHITE).setCubic(true);
        List<Line> lines = new ArrayList<>();
        line.setHasPoints(false);
        line.setColor(AttrUtil.getAttributeColor(mContext, R.attr.chart_line));
        lines.add(line);

        LineChartData data = new LineChartData();
        data.setLines(lines);

        //Axis
        Axis axisX = new Axis().setHasLines(true).setHasSeparationLine(false).setLineColor(AttrUtil.getAttributeColor(mContext, R.attr.default_background));
        Axis axisY = new Axis().setHasLines(true).setHasSeparationLine(false).setLineColor(AttrUtil.getAttributeColor(mContext, R.attr.default_background));

        axisX.setFormatter(new AxisValueFormatter() {
            @Override
            public int formatValueForManualAxis(char[] formattedValue, AxisValue axisValue) {
                return 1;
            }

            @Override
            public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits) {
                return 1;
            }
        });

        data.setAxisXBottom(axisX);
        data.setAxisYLeft(axisY);

        mMarketCapChart.setInteractive(false);
        mMarketCapChart.setLineChartData(data);
    }



    private static class CustomFormatter extends SimpleAxisValueFormatter {
        private float scale;
        private float sub;
        private int decimalDigits;

        public CustomFormatter(float scale, float sub, int decimalDigits) {
            this.scale = scale;
            this.sub = sub;
            this.decimalDigits = decimalDigits;
        }

        @Override
        public int formatValueForAutoGeneratedAxis(char[] formattedValue, float value, int autoDecimalDigits) {
            float scaledValue = (value + sub) / scale;
            return super.formatValueForAutoGeneratedAxis(formattedValue, scaledValue, this.decimalDigits);
        }

    }
}
